version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - custom-dictionary
words: []
ignoreWords:
  - accountexpires
  - displayname
  - memberof
  - objectclass
  - samaccountname
  - useraccountcontrol
import: []
