version: "3.7"
services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    command: "--copy-service --loglevel debug"
    environment:
      - LDAP_ORGANISATION=mock.ad
      - LDAP_DOMAIN=mock.ad.com
      - "LDAP_BASE_DN=dc=mock,dc=ad,dc=com"
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
    volumes:
      - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    ports:
      - 389:389
      - 636:636
    networks:
      - openldap

  # docker-compose --profile ldapadmin up
  phpldapadmin:
    profiles:
      - ldapadmin
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - "80:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - openldap

networks:
  openldap:
    driver: bridge
