name: build_and_release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  build_and_release:
    strategy:
      fail-fast: false
      matrix:
        go: [1.23.4]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: Build and release ldap-cli
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pass keyring
        run: ./scripts/setup/keyring.sh
        shell: bash

      - name: Install upx
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Install go tools
        run: |
          go install golang.org/x/tools/gopls@latest && \
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest && \
          go install github.com/axw/gocov/gocov@latest

      - name: Export Module Name
        id: export_module_name
        run: echo "MODULE_NAME=$(go mod edit -json | jq -r '.Module.Path')" >> "$GITHUB_OUTPUT"

      - name: Run linters
        run: gofmt -s -d ./ && golangci-lint run -v

      - name: Setup openldap mock-up
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./oat/docker-compose.yml"

      - name: Run tests with coverage
        run: gocov test ./... -coverprofile=c.out
        env:
          TEST_OAT: "true"

      - name: Publish code coverage  
        uses: qltysh/qlty-action/coverage@v1
        with:
          files: ./c.out
          format: coverprofile
          add-prefix: ${{ steps.export_module_name.outputs.MODULE_NAME }}
          verbose: true
          oidc: true

      - name: Precompile binaries and upload assets
        uses: cli/gh-extension-precompile@v1
        with:
          build_script_override: "scripts/build.sh"
          go_version: ${{ matrix.go }}

      - name: Update code documentation
        run: curl -fsSL https://proxy.golang.org/${{ steps.export_module_name.outputs.MODULE_NAME }}/@v/${{ github.ref_name }}.info
