name: build_and_release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  build_and_release:
    strategy:
      fail-fast: false
      matrix:
        go: [1.21]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: Build and release ldap-cli
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install upx
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Update gopls
        run: go install golang.org/x/tools/gopls@latest
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Run linters
        run: gofmt -s -d ./ && golangci-lint run -v
      - name: Setup openldap mock-up
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./oat/docker-compose.yml"
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          TEST_OAT: "true"
          CC_TEST_REPORTER_ID: "1e15987ddde9b2a41bf176f0fbf3b7fb8d5be5469e99976ce75b0d1453d32579"
        with:
          coverageCommand: go test -v -coverprofile=c.out ./...
          debug: true
      - name: Precompile binaries and upload assets
        uses: cli/gh-extension-precompile@v1
        with:
          build_script_override: "scripts/build.sh"
          go_version: ${{ matrix.go }}
